--liquibase formatted sql
--changeset antoxakon:1  -- Формат: author:id
--comment: create table books

CREATE TABLE book_master (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    title varchar(200) NOT NULL DEFAULT 'book1',
    author varchar(200) NOT NULL
) PARTITION BY LIST (author);

CREATE TABLE books_author PARTITION OF book_master
FOR VALUES IN ('Anton');

CREATE TABLE books_kiska PARTITION OF book_master
FOR VALUES IN ('Kiska');